version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: csym
      MYSQL_USER: airah
      MYSQL_PASSWORD: airah
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
